services:
  gerador_pdf:
    image: node:18
    container_name: gerador_pdf
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    environment:
      NODE_ENV: ${NODE_ENV}
      API_KEY: ${SECRET_KEY}

      MAIL_ADRESS: ${MAIL_ADRESS}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}

      CORS_ORIGINS: ${CORS_ORIGINS}

      APPLICATION_PORT: 3000
    ports:
      - ${APPLICATION_PORT}:3000
    networks:
      dokploy-network:
        aliases:
          - sap_prefeitura
networks:
  dokploy-network:
    external: true